### ISSUE TITLE
Problems with Movie2Serial

### ISSUE THREAD

**Issue by dirkblaze** [i-make-robots/LEDWall#1]
have tried to get this working many time.  Using your code "practically verbatim" - only changing the name of the input video file - we get these errors every time:

 Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
    at javax.swing.ToolTipManager.initiateToolTip(ToolTipManager.java:478)
    at javax.swing.ToolTipManager.mouseEntered(ToolTipManager.java:435)
    at processing.mode.java.pdex.JavaTextArea$MouseHandler.mouseEntered(JavaTextArea.java:898)
    at java.awt.AWTEventMulticaster.mouseEntered(AWTEventMulticaster.java:300)
    at java.awt.Component.processMouseEvent(Component.java:6544)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6300)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4891)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.retargetMouseEnterExit(Container.java:4676)
    at java.awt.LightweightDispatcher.trackMouseEnterExit(Container.java:4654)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4505)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
error, disabling movieEvent() for /Users/jodysweitzer/Documents/TheArray/AviClub/mga.avi
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at processing.video.Movie.fireMovieEvent(Unknown Source)
    at processing.video.Movie.invokeEvent(Unknown Source)
    at processing.video.Movie$2.rgbFrame(Unknown Source)
    at org.gstreamer.elements.RGBDataAppSink$AppSinkNewBufferListener.newBuffer(RGBDataAppSink.java:162)
    at org.gstreamer.elements.AppSink$2.callback(AppSink.java:184)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:485)
    at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:515)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 2400
    at movie2serial0516.image2data(movie2serial0516.java:193)
    at movie2serial0516.movieEvent(movie2serial0516.java:130)
    ... 15 more

Please advise!!! Have tried various parameters (screen height, width etc) and various video files.
Always the same result, seems to be generated but the "image2data" procedure, tho I'm not absolutely positive.  

In debug all the variables seem ok - then it blows up!!!

Please help!!!

**Comment by dirkblaze** [comment]
btw: running Processing 3.0.2 on Mac OS X 10.11.4

**Comment by i-make-robots** [comment]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 2400
at movie2serial0516.image2data(movie2serial0516.java:193)
at movie2serial0516.movieEvent(movie2serial0516.java:130)

Aha!  That looks like the last point in my code before things go sideways.

**Comment by i-make-robots** [comment]
There must be more than a simple change.  line 193 is not even in image2data(), which goes from lines 150 to 172.  Somehow you've gained 20 lines, minimum.

**Comment by dirkblaze** [comment]
I've tried several different versions of Movie2Serial including yours verbatim.  They all blow up like this.  I will run it again with yours.
